
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
// #include <react/renderer/components/RTNCardViewSpecs/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {
RNCardViewProps::RNCardViewProps(const PropsParserContext &context, const RNCardViewProps &sourceProps,
                                 const RawProps &rawProps)
    : ViewProps(context, sourceProps, rawProps),


      backgroundcolor(convertRawProp(context, rawProps, "backgroundcolor", sourceProps.backgroundcolor, 0)),
      cornerRadius(convertRawProp(context, rawProps, "cornerRadius", sourceProps.cornerRadius, {0.0})),
      cardElevation(convertRawProp(context, rawProps, "cardElevation", sourceProps.cardElevation, {0.0})),
      cardMaxElevation(convertRawProp(context, rawProps, "cardMaxElevation", sourceProps.cardMaxElevation, {0.0})),
      useCompatPadding(convertRawProp(context, rawProps, "useCompatPadding", sourceProps.useCompatPadding, {false})),
      cornerOverlap(convertRawProp(context, rawProps, "cornerOverlap", sourceProps.cornerOverlap, {true})) {}


} // namespace react
} // namespace facebook