
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */

#ifndef HARMONY_CARDVIEW_SRC_MAIN_CPP_PROPS_H
#define HARMONY_CARDVIEW_SRC_MAIN_CPP_PROPS_H

#include "ReactCommon/TurboModule.h"
#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include "glog/logging.h"
namespace facebook {
namespace react {

class JSI_EXPORT RNCardViewProps final : public ViewProps {
 public:
  RNCardViewProps() = default;
  RNCardViewProps(const PropsParserContext &context, const RNCardViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props
  int backgroundcolor{0};   //卡片的背景色
  Float cornerRadius{0.0};  //卡片的圆角大小
  Float  cardElevation{0.0};  //阴影的大小
  Float cardMaxElevation{0.0};  //阴影的最大高度
  bool useCompatPadding{false}; //是否设置内边距
  bool cornerOverlap{true};   //使内容不会与圆角重叠
};
} // namespace react
} // namespace facebook

#endif